import math

SCALE = 1.0

# General Dimensions
BASIN_SIZE = 170.0 * SCALE
BASIN_HEIGHT = 170.0 * SCALE
WALL_THICKNESS = 4.0 * SCALE

# Outlet Openings
OUTLET_DIAMETER = 106.0  # Increased to support 4-inch inner bore plus wall thickness
OUTLET_HEIGHT_OFFSET = 25.0 * SCALE
THREAD_NOMINAL_RADIUS = 55.0

# Grate
GRATE_THICKNESS = 15.0 * SCALE
GRATE_LIP_WIDTH = 10.0 * SCALE
GRATE_SLOT_WIDTH = 12.0 * SCALE
GRATE_RIB_THICKNESS = 6.0 * SCALE

# Adapter
ADAPTER_OUTER_DIAMETER = 103.6 # 4 inch plus 1mm thickness
ADAPTER_INNER_DIAMETER = 101.6  # 4 inch pipe
ADAPTER_FLANGE_DIAMETER = OUTLET_DIAMETER + 30.0
ADAPTER_LENGTH = 80.0
ADAPTER_TOLERANCE = 0.5

# Plug
PLUG_DIAMETER = OUTLET_DIAMETER - ADAPTER_TOLERANCE * 2
PLUG_THICKNESS = 5.0 * SCALE
PLUG_FLANGE_DIAMETER = ADAPTER_FLANGE_DIAMETER

# Cutout guide for bottom (thickness to leave)
CUTOUT_GUIDE_THICKNESS = 1.0 * SCALE
